language: java
sudo: required
services:
  - docker
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jobs:
  include:
    - stage: test
      name: Build on OpenJDK 8
      jdk: openjdk8
      script: ./gradlew --no-daemon -i --stacktrace jacocoTestReport
      after_success: bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
