language: java
sudo: required
services:
  - docker
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "aesteve-github"
    token:
      secure: "IL+4jI3bm/04UWzSpzDx/zTvcKEWWB3iR8t9WDxEx/id8RspRDTZYpnwgqNmxGSdhpPJuTb0xgm60OWbtKeerl0kwfyamJD50A8g9+aFb6mzfuxxAwNHrbcrAnN/KtVOSflksgtB+/hXsBuF7zhVS92sUrZlMaz/dMS/2Ioq99bHUOGDw/4QW6TAFn6zCvvpEsyEwICRaOJqNQ7Je1xpwP3Az5QtvnG/H0XaVNuUJ5LfD6vEor6c6hBa79dA3hhXdYMAyycNSXpAvVsn2sb7GXap23NdtjRz1oYS4w6pbIz20Ba9LtD13Lve0+ZQU1Z3xNYtY+DaeraSzV9d1/nF79YmHV3D460s2zz8m+Z8XFHgsLAG7DiXm0g4RH9EtlBxmTy5F67OntEg3or98V/Ir9b8mWjNU+Bxw9lpALwGbX914rnVVcYzPVo/Vzjj5dNMDIURNHy7it08yRf4swsGzTRApnZHKt3qJH5ItTVA7qF19a7OOQph4LnZe3v4gV6b2YdoC2SHi/8FLbNv8r6z8M+hcmI74dNSMKU8gA1wi/5Lyz5Kmt9j78Y25CJW1kSt1z1shWO35dk6Gu8Er86E9DhR4opztJ60O9vVMqTDhA0+uJ5Fp3XbqYApeNObba9qQS2dLtsgoJ6e9EpwR0peXEUBrFbeiMKob6oja8qSXO4="
script: ./gradlew -Dsonar.host.url=https://sonarcloud.io/ -Dtests.integration=localstack jacocoTestReport sonarqube
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
