# When a tag matching a semver number (like `1.1.0`) is pushed, then tyr to publish the version to bintray and create the matching release in Github
name: CI-Release
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Releases the version to Bintray
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.3
          arguments: test bintrayUpload
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@v2
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
