# When a tag matching a semver number (like `1.1.0`) is pushed, then tyr to publish the version to bintray and create the matching release in Github
name: CI-Release
on:
  push:
    tags:
      - RELEASE-*

jobs:
  publish-release-bintray:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Release to Bintray
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.3
          arguments: test bintrayUpload
        env:

      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@v2
        with:
          version_regex: ^RELEASE-[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
