# Always tests on every branch push / PR / master
name: CI-Snapshot
on:
  push:
    tags: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+\.*SNAPSHOT

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.3
          arguments: assemble publish -PossrhUsername=${{secrets.SONATYPE_NEXUS_USERNAME}} -PossrhPassword=${{secrets.SONATYPE_NEXUS_PASSWORD}}
